### ISSUE TITLE
[Bug Skip] test_ts2ep_convert_quantized_model1 fails on XPU: TS->EP allclose mismatch on quantized model

### ISSUE THREAD

**Issue by daisyden** [intel/torch-xpu-ops#3531]
## Bug Description

`TestConverter.test_ts2ep_convert_quantized_model1` in
`test/xpu/export/test_converter_xpu.py` fails on XPU with an `allclose`
mismatch: the converted ExportedProgram output diverges numerically from
the original TorchScript output for a quantized model.

## Affected Tests

Cases:
~~op_ut,third_party.torch-xpu-ops.test.xpu.export.test_converter_xpu.TestConverter,test_ts2ep_convert_quantized_model1~~

## Error Message

```
File ".../test/xpu/export/test_converter_xpu.py:1457, in
        test_ts2ep_convert_quantized_model1
    self._check_tensor_list_equal(orig_out, ep_out)
File ".../test/xpu/export/test_converter_xpu.py:119, in
        _check_tensor_list_equal
    self.assertTrue(torch.allclose(x, y))
AssertionError: False is not true
```

Captured stderr:
```
W0429 07:16:00.915000 site-packages/torch/_export/non_strict_utils.py:654]
    dimension inputs['x_1'].shape[1] 0/1 specialized;
    Dim.AUTO was specified along with a sample input with hint = 1.
```

## Reproduction

```bash
cd $HOME/daisy_pytorch/third_party/torch-xpu-ops/test/xpu
pytest -v export/test_converter_xpu.py::TestConverter::test_ts2ep_convert_quantized_model1
```

## Root Cause Analysis

`test_ts2ep_convert_quantized_model1` runs the TS→EP converter on a
quantized model and asserts the converted ExportedProgram produces the
same outputs as the original TorchScript module. On XPU this fails with
`allclose=False`. The converter or the underlying quantized op lowering
produces numerically different output on XPU than CPU/CUDA. The captured
warning about `Dim.AUTO` specialization suggests dynamic-shape handling
during export may also differ between paths.

This test was not introduced by PR #3475 (it lives on `main` in
`test/xpu/export/test_converter_xpu.py`); it surfaces in PR #3475's
`linux-ut (op_ut) / summary` artifact only because no tracking issue
currently covers it for the dynamic-skip filter.

## Context

This issue tracks an XPU export/quantization gap surfaced (but not
introduced) by PR [#3475](https://github.com/intel/torch-xpu-ops/pull/3475).
PR #3475 enables broader CUDA test coverage on XPU; the failing case is
**enabled-but-failing** but originates outside PR #3475's diff scope.

For PR #3475 to land green, this issue must be `skipped`-labeled with the
`Cases:` line above so the `ut_result_check.sh` filter stops flagging it as
a new failure. Once the underlying TS→EP-on-quantized-model gap is fixed,
the dynamic-skip entry can be removed and the test will pass without
further code changes.

PR: https://github.com/intel/torch-xpu-ops/pull/3475

## Versions

PyTorch: 2.13.0.dev (April 2026 nightly)
Hardware: Intel Data Center GPU Max 1100/1550

## Labels

- `skipped`
- `module: ut`

**Comment by Silv3S** [comment]
Failed in recent CI - https://github.com/intel/torch-xpu-ops/actions/runs/25650590468/job/75464321686?pr=3535

**Comment by pponikox** [comment]
Hi @Silv3S, and thanks for the info 👍 
This test was randomly failing when I reproduced it locally - around 10% of runs ended with a `False is not True` error.
I verified that the problem was caused by a difference in test's `setUp()` logic between the XPU version and upstream. The patch is already added and once it gets merged the test should pass 100% of cases.

**Comment by Silv3S** [comment]
Let's keep it open until nightly passes

**Comment by pponikox** [comment]
> Let's keep it open until nightly passes

I believe that GitHub Actions bot didn't strike out this test due to the fact that "random" label was present.
I've checked last two `Nightly / Build-from-source` builds ([link1](https://github.com/intel/torch-xpu-ops/actions/runs/26404903737/job/77739636923), [link2](https://github.com/intel/torch-xpu-ops/actions/runs/26362930106/job/77614067030)) and in both of them this test passed:
```
...
2026-05-26T00:59:14.0602731Z export/test_converter_xpu.py::TestConverter::test_convert_if_duplicate_attr_names 
2026-05-26T00:59:14.0603242Z [gw1] [ 58%] PASSED export/test_converter_xpu.py::TestConverter::test_aten_tensor_dynamic 
2026-05-26T00:59:14.0910199Z export/test_converter_xpu.py::TestConverter::test_prim_min 
2026-05-26T00:59:14.0924464Z [gw6] [ 60%] PASSED export/test_converter_xpu.py::TestConverter::test_ts2ep_convert_quantized_model1 
2026-05-26T00:59:14.0925819Z [gw2] [ 62%] PASSED export/test_converter_xpu.py::TestConverter::test_convert_if_duplicate_attr_names 
2026-05-26T00:59:14.0995200Z export/test_converter_xpu.py::TestConverter::test_ts2ep_convert_quantized_model_with_opcontext 
...
```

That being said I removed the "random" label and now we'll see if the test is correctly marked as passing 😉

**Comment by Silv3S** [comment]
Good catch with that `random` label
